name: Build and Deploy to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy dist to deploy branch        # 👈 guion alineado con los otros pasos
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}    # PAT guardado como secreto
          publish_dir: ./dist
          publish_branch: deploy
          allow_empty_commit: true
          user_name: FernyDev
          user_email: fernydev@example.com




